export const DASHBOARDS_BASE_PATH = '/console/dashboard'
export const DATA_LIBRARY_BASE_PATH = '/console/data-library'
export const DATASETS_BASE_PATH = '/console/dataset'
export const DATASETS_RUNS_BASE_PATH = '/console/dataset/run'
export const GEOMETRIES_BASE_PATH = '/console/geometries'
export const GEOMETRIES_RUNS_BASE_PATH = '/console/geometries/run'
export const GEOMETRIES_RUNS_OUTPUTS_BASE_PATH = '/console/geometries/output'
export const PRODUCTS_BASE_PATH = '/console/product'
export const PRODUCTS_RUNS_BASE_PATH = '/console/product/run'
export const PRODUCTS_RUNS_OUTPUTS_BASE_PATH = '/console/product/output'
export const REPORTS_BASE_PATH = '/console/report'
export const INDICATORS_BASE_PATH = '/console/indicator'
export const INDICATORS_DERIVED_BASE_PATH = '/console/indicator/derived'
export const INDICATORS_MEASURED_BASE_PATH = '/console/indicator/measured'
export const SUPER_ADMIN_AUDIT_LOGS_BASE_PATH =
  '/console/super-admin/audit-logs'
export const SUPER_ADMIN_ORGANIZATIONS_BASE_PATH =
  '/console/super-admin/organizations'
export const USERS_BASE_PATH = '/console/super-admin/users'
export const WORKSPACE_BASE_PATH = '/console/workspace'
export const LOGS_BASE_PATH = '/console/logs'
export const LOGIN_BASE_PATH = '/login'
export const ACCOUNT_DETAILS_BASE_PATH = '/console/me/account'
export const API_KEYS_BASE_PATH = '/console/me/api-keys'
export const TWO_FACTOR_BASE_PATH = '/console/me/two-factor'
